#ifndef LOTUS_VERSION_H
#define LOTUS_VERSION_H

/* Automatically generated by cmake */

#define LOTUS_VERSION_STRING "1.3.1"
#define LOTUS_VERSION_MAJOR  1
#define LOTUS_VERSION_MINOR  3
#define LOTUS_VERSION_PATCH  1

#endif // LOTUS_VERSION_H
