// Auto generated by generate_emoji_header.py
#ifndef EMOJI_DATA_H
#define EMOJI_DATA_H

#include <vector>
#include <string>

struct EmojiEntry {
    std::string trigger;
    std::string output;
};

extern const std::vector<EmojiEntry> EMOJI_LIST;

#endif // EMOJI_DATA_H
