import json
import os


def hex_to_emoji(hex_str):
    segments = hex_str.split("-")
    return "".join(chr(int(s, 16)) for s in segments)


def generate_files(json_file, header_file, cpp_file):
    try:
        with open(json_file, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error reading JSON: {e}")
        return

    emoji_entries = []

    for key, emoji_data in data.items():
        hex_code = emoji_data.get("code_points", {}).get("output", "")
        if not hex_code:
            continue

        emoji_char = hex_to_emoji(hex_code)

        triggers = []
        if "shortname" in emoji_data:
            triggers.append(emoji_data["shortname"])
        if "shortname_alternates" in emoji_data:
            triggers.extend(emoji_data["shortname_alternates"])
        if "ascii" in emoji_data:
            triggers.extend(emoji_data["ascii"])

        for t in triggers:
            safe_t = t.replace('"', '\\"').replace('\\', '\\\\')
            emoji_entries.append((safe_t, emoji_char))

    emoji_entries.sort(key=lambda x: x[0])

    with open(header_file, "w", encoding="utf-8") as f:
        f.write("// Auto generated by generate_emoji_header.py\n")
        f.write("#ifndef EMOJI_DATA_H\n")
        f.write("#define EMOJI_DATA_H\n\n")
        f.write("#include <vector>\n")
        f.write("#include <string>\n\n")

        f.write("struct EmojiEntry {\n")
        f.write("    std::string trigger;\n")
        f.write("    std::string output;\n")
        f.write("};\n\n")

        f.write("extern const std::vector<EmojiEntry> EMOJI_LIST;\n\n")
        f.write("#endif // EMOJI_DATA_H\n")

    with open(cpp_file, "w", encoding="utf-8") as f:
        f.write("// Auto generated by generate_emoji_header.py\n")
        f.write(f'#include "{os.path.basename(header_file)}"\n\n')

        f.write("const std::vector<EmojiEntry> EMOJI_LIST = {\n")
        for trigger, output in emoji_entries:
            f.write(f'    {{"{trigger}", "{output}"}},\n')
        f.write("};\n")


if __name__ == "__main__":
    generate_files("emojione.json", "emoji_data.h", "emoji_data.cpp")
